version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: "${UID}:${GID}"
    ports:
      - "${PORT}:8080"
    volumes:
      - "${DOCKER_STATIC_HOSTING}:/data"
      - "./config:/config"
    environment:
      FB_BASEURL: "/filebrowser"
    restart: always
    networks:
      - https

networks:
  https:
    external:
      name: ${HTTPS_NETWORK}
